# Generated by Django 2.2.7 on 2020-01-01 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('salary_range', models.CharField(max_length=50)),
                ('salary_estimated', models.FloatField(default=0)),
                ('post_img', models.CharField(max_length=255)),
                ('post_url', models.CharField(max_length=255)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(default='empty', max_length=150)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('vector', models.TextField(default='')),
                ('fixed_vector', models.TextField(default='')),
            ],
        ),
    ]
