# Generated by Django 2.1.4 on 2019-09-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vector',
            field=models.TextField(default=''),
        ),
    ]
