# Generated by Django 2.1.5 on 2020-01-02 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fixed_vector',
        ),
        migrations.RemoveField(
            model_name='post',
            name='salary_estimated',
        ),
    ]
