# Generated by Django 2.1.4 on 2019-09-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default='empty', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.CharField(default='empty', max_length=50),
        ),
    ]
