# Generated by Django 2.1.4 on 2019-08-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='salary_range',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
