# Generated by Django 2.1.4 on 2019-09-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0003_vocabulary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('num_of_searches', models.IntegerField(default=0)),
                ('status_type', models.IntegerField(default=0)),
            ],
        ),
    ]
