# Generated by Django 2.1.4 on 2019-09-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0004_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
